In [2]:
import numpy as np 

np_array1 = np.array([1,2,3,4])
print(np_array1)

np_array1[:]

np_array1[0:2]

np_array1[1] = 100


np_mul_array1 = np.array([[1,2,3],
[2,3,4],
[3,4,5]])

print(np_mul_array1.shape)
np_mul_array1[0]

np_mul_array2 = np.array([[1,2,3], [2,3,5]], dtype= 'float32')



#filling array
np_array2 = np.full((2,3,4), 5)
print(np_array2)

np_array3 = np.zeros((5,6,4))
print(np_array3)

np_array_empty = np.empty((3,3,3))

#generate a sequence of values
np_range = np.arange(0,20,3)
print(np_range)
np_linspace = np.linspace(0,10, 100)
print(np_linspace)


#nan and inf
print(np.nan) #not a number value
print(np.inf) #infinity value type

print(np.isnan(np.nan))

#from python list to np array

list1 = [1,2,3,4]
list2= [3,4,5,6]

np_array4 = np.array(list1)
np_array5 = np.array(list2)

print(f'list1*5 = {list1*5}')
print(f'np_array5*5 = {np_array4*5}')


#print(f'list1+5 = {list1+5}')
print(f'np_array5+5 = {np_array4+5}')



[1 2 3 4]
(3, 3)
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[ 0  3  6  9 12 15 18]
[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.2

In [4]:
#stacking array in numpy
a = np.array([[1, 2], 
			[3, 4]]) 

b = np.array([[5, 6], 
			[7, 8]]) 

# vertical stacking 
print( np.vstack((a, b))) 

# horizontal stacking 
print( np.hstack((a, b))) 

c = [5, 6] 

# stacking columns 
print("\nColumn stacking:\n", np.column_stack((a, c))) 

# concatenation method 
print("\nConcatenating to 2nd axis:\n", np.concatenate((a, b), 1)) 


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


In [5]:
#spliting np array
a = np.array([[1, 3, 5, 7, 9, 11], 
			[2, 4, 6, 8, 10, 12]]) 

# horizontal  
print(np.hsplit(a, 2)) 

# vertical  
print( np.vsplit(a, 2))


[array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]
[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [7]:
# creating a numpy array 
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]) 

# printing array 
print("Array: " + str(array)) 

# reshaping numpy array 
# converting it to 2-D from 1-D array 
reshaped1 = array.reshape((4, array.size//4)) 

# printing reshaped array 
print("First Reshaped Array:") 
print(reshaped1) 

# creating another reshaped array 
reshaped2 = np.reshape(array, (2, 8)) 

# printing reshaped array 
print("\nSecond Reshaped Array:") 
print(reshaped2)


Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Second Reshaped Array:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [8]:
# Flatening numpy array 
list_1 = [1, 2, 3, 4] 
list_2 = [5, 6, 7, 8] 
arr = np.array([list_1, list_2]) 

print(arr.flatten())


[1 2 3 4 5 6 7 8]


In [9]:
# Creating a different copy of NumPy 
# array creating copy of array 
c = arr.copy() 
	
# both arr and c have different id 
print("id of arr:", id(arr)) 
print("id of c:", id(c)) 
	
# changing original array 
# this will not effect copy 
arr[0] = 12
	
# printing array and copy 
print("original array:", arr) 
print("copy:", c)


id of arr: 1230132905712
id of c: 1230132908784
original array: [[12 12 12 12]
 [ 5  6  7  8]]
copy: [[1 2 3 4]
 [5 6 7 8]]


In [10]:
# Creating a view of a 
# NumPy array 
# creating view 
v = arr.view() 
	
# both arr and v have different id 
print("id of arr:", id(arr)) 
print("id of v:", id(v)) 
	
# changing original array 
# will effect view 
arr[0] = 12
	
# printing array and view 
print("original array:", arr) 
print("view:", v)


id of arr: 1230132905712
id of v: 1230132907344
original array: [[12 12 12 12]
 [ 5  6  7  8]]
view: [[12 12 12 12]
 [ 5  6  7  8]]
